# Generated by Django 6.1.1 on 2026-09-02 22:19

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wallet_address', models.CharField(db_index=True, help_text='Stellar public key (G...)', max_length=56, unique=True)),
                ('role', models.CharField(choices=[('POSTER', 'Poster'), ('CONTRIBUTOR', 'Contributor')], default='CONTRIBUTOR', max_length=12)),
                ('bio', models.TextField(blank=True, default='')),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bounty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('skill_category', models.CharField(choices=[('DEVELOPMENT', 'Development'), ('DESIGN', 'Design'), ('WRITING', 'Writing'), ('VIDEO', 'Video Creation'), ('PROJECT_MANAGEMENT', 'Project Management'), ('COMMUNITY', 'Community')], max_length=20)),
                ('reward_amount', models.DecimalField(decimal_places=7, help_text='Amount in the chosen asset (7 decimals for Stellar precision)', max_digits=20)),
                ('reward_asset', models.CharField(choices=[('XLM', 'XLM'), ('USDC', 'USDC')], default='XLM', max_length=4)),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('POSTED', 'Posted'), ('CLAIMED', 'Claimed'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='POSTED', max_length=10)),
                ('escrow_tx_hash', models.CharField(blank=True, default='', help_text='Stellar tx hash for the escrow funding transaction', max_length=64)),
                ('escrow_bounty_id', models.CharField(blank=True, default='', help_text='On-chain bounty ID from the Soroban contract', max_length=128)),
                ('payment_tx_hash', models.CharField(blank=True, default='', help_text='Stellar tx hash for the payout transaction', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_bounties', to=settings.AUTH_USER_MODEL)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_bounties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'bounties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_text', models.TextField(help_text='Description of the completed work')),
                ('submission_url', models.URLField(blank=True, default='', help_text='Link to the deliverable (GitHub PR, Figma, Google Doc, etc.)')),
                ('reviewer_notes', models.TextField(blank=True, default='', help_text='Feedback from the poster')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REVISION_REQUESTED', 'Revision Requested')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.bounty')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('tx_type', models.CharField(choices=[('FUND_ESCROW', 'Fund Escrow'), ('RELEASE_PAYMENT', 'Release Payment'), ('REFUND', 'Refund')], max_length=16)),
                ('from_address', models.CharField(max_length=56)),
                ('to_address', models.CharField(max_length=56)),
                ('amount', models.DecimalField(decimal_places=7, max_digits=20)),
                ('asset', models.CharField(max_length=4)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.bounty')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
