# Generated by Django 6.1.1 on 2026-09-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_url',
            field=models.URLField(blank=True, default='', help_text='Link to the deliverable (GitHub PR, Figma, Google Doc, etc)'),
        ),
    ]
