# Generated by Django 6.1.1 on 2026-09-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_submission_submission_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='status',
            field=models.CharField(choices=[('POSTED', 'Posted'), ('CLAIMED', 'Claimed'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('EXPIRED', 'Expired')], db_index=True, default='POSTED', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
