# Generated by Django 6.1.1 on 2026-09-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_bounty_status_alter_transaction_tx_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text='List of contributor skills or specialties (e.g. Frontend Developer, Backend Engineer)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(blank=True, db_index=True, help_text='Stellar public key (G...)', max_length=56, null=True, unique=True),
        ),
    ]
