# Generated by Django 6.1.1 on 2026-09-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_skills_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text='Social and portfolio links (e.g. github, x, linkedin, portfolio)'),
        ),
    ]
