import type { Metadata } from "next";
import { Manrope } from "next/font/google";
const manrope = Manrope({subsets:['latin'],variable:'--font-sans'}); 
import "./globals.css";
import { cn } from "@/lib/utils";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", "font-sans", manrope.variable)}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
