"""
Django settings for ÉréEARN project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import dj_database_url
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", cast=bool)

_allowed_hosts_config = config("ALLOWED_HOSTS", default="*", cast=Csv())
if "*" in _allowed_hosts_config:
    ALLOWED_HOSTS = ["*"]
else:
    ALLOWED_HOSTS = list(
        set([h.strip() for h in _allowed_hosts_config if h.strip()] + ["localhost", "127.0.0.1", "web", "0.0.0.0"])
    )


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "django_filters",
    "drf_spectacular",
    "api",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Core.wsgi.application"

import sys

DATABASE_URL = config("DATABASE_URL", default="")
if "test" in sys.argv:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": ":memory:",
        }
    }
elif DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATA_DIR = BASE_DIR / "data"
    if DATA_DIR.exists():
        DEFAULT_DB_PATH = DATA_DIR / "db.sqlite3"
    else:
        DEFAULT_DB_PATH = BASE_DIR / "db.sqlite3"

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": config("DATABASE_PATH", default=str(DEFAULT_DB_PATH)),
        }
    }

AUTH_USER_MODEL = "api.User"

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "ÉréEARN API",
    "DESCRIPTION": "Headless REST API for Soroban Escrow & Bounty Marketplace on Stellar Testnet.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "TAGS": [
        {"name": "Authentication", "description": "Email/password registration, login, wallet authentication, and profile management"},
        {"name": "Bounties", "description": "Bounty discovery, funding preparation, creation, and claiming"},
        {"name": "Submissions", "description": "Deliverable submissions and review processing"},
        {"name": "Dashboards", "description": "Aggregated stats for contributors and posters"},
        {"name": "Transactions", "description": "Stellar on-chain escrow transaction audit log"},
    ],
    "ENUM_NAME_OVERRIDES": {
        "BountyStatusEnum": "api.models.Bounty.Status",
        "SubmissionStatusEnum": "api.models.Submission.Status",
        "TransactionStatusEnum": "api.models.Transaction.Status",
    },
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
}



CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = config("CORS_ALLOWED_ORIGINS", cast=Csv())


# Stellar / Soroban Configuration

STELLAR_NETWORK = config("STELLAR_NETWORK")
STELLAR_HORIZON_URL = config("STELLAR_HORIZON_URL")
STELLAR_NETWORK_PASSPHRASE = config("STELLAR_NETWORK_PASSPHRASE")
STELLAR_ESCROW_SECRET = config("STELLAR_ESCROW_SECRET")
STELLAR_ESCROW_PUBLIC = config("STELLAR_ESCROW_PUBLIC")
SOROBAN_RPC_URL = config("SOROBAN_RPC_URL")
SOROBAN_CONTRACT_ID = config("SOROBAN_CONTRACT_ID")

# Stellar Asset Contract (SAC) addresses for Soroban token transfers.
# These are DIFFERENT from SOROBAN_CONTRACT_ID (the escrow contract).
# XLM SAC on Testnet: CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC
# (derived via: Asset.native().contract_id(network_passphrase))
SOROBAN_XLM_CONTRACT_ID = config(
    "SOROBAN_XLM_CONTRACT_ID",
    default="CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC",
)
SOROBAN_USDC_CONTRACT_ID = config(
    "SOROBAN_USDC_CONTRACT_ID",
    default="CBIELTK6YBZJU5UP2WWQEUCYKLPU6AUNZ2BQ4WWFEIE3USCIHMXQDAMA",
)

# USDC Test Asset
USDC_ASSET_CODE = config("USDC_ASSET_CODE", default="USDC")
USDC_ASSET_ISSUER = config(
    "USDC_ASSET_ISSUER",
    default="GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5",
)


REDIS_URL = config("REDIS_URL", default=config("CELERY_BROKER_URL", default=""))
if "test" in sys.argv:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "ÉréEARN-test-cache",
        }
    }
elif REDIS_URL and REDIS_URL.startswith("redis"):
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "ÉréEARN-cache",
        }
    }



LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "api": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}
